[build]
  command = "yarn run build"
  publish = ".next"

[dev]
  command = "yarn dev -p 3001"
  port = 3000
  targetPort = 3001

[context.dev]
  environment = { NEXT_PUBLIC_APP_URL = "http://localhost:3000" }
